version: '3'

services:
  pokedexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '${PORT}:${PORT}'
    # working_dir: /var/www/pokedex
    environment:
      MONGO_URL: ${MONGO_URL}
      PORT: ${PORT}
      API_URL: ${API_URL}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5.0.0
    container_name: mongo-pokedex-cluster
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pokemon
    volumes:
      - ./mongo:/data/db
